[package]
name = "bpaf"
version = "0.4.7"
edition = "2021"
categories = ["command-line-interface"]
description = "A simple Command Line Argument Parser with parser combinators"
keywords = ["args", "arguments", "cli", "parser", "parse"]
authors = [ "Michael Baykov <manpacket@gmail.com>" ]
readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/pacak/bpaf"
rust-version = "1.56"

[dependencies]
bpaf_derive = { path = "./bpaf_derive", version = "0.1", optional = true }

[dev-dependencies]
strum = { version = "0.24", features = ["derive"] }
bpaf = { path = ".",  features = ["derive"] }


[package.metadata.docs.rs]
features = ["bpaf_derive"]


[features]
derive = ["bpaf_derive"]

[workspace]
members = [".", "./bpaf_derive"]
