[package]
name = "bpaf"
version = "0.5.4"
edition = "2021"
categories = ["command-line-interface"]
description = "A simple Command Line Argument Parser with parser combinators"
keywords = ["args", "arguments", "cli", "parser", "parse"]
authors = [ "Michael Baykov <manpacket@gmail.com>" ]
readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/pacak/bpaf"
rust-version = "1.56"

[dependencies]
bpaf_derive = { path = "./bpaf_derive", version = "0.2.0", optional = true }

[dev-dependencies]
bpaf = { path = ".",  features = ["derive", "extradocs"] }


[package.metadata.docs.rs]
features = ["derive", "extradocs"]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples=examples"]


[features]
derive = ["bpaf_derive"]
extradocs = []
batteries = []

[workspace]
members = [".", "./bpaf_derive"]
