[package]
name = "bpaf"
version = "0.3.2"
edition = "2021"
categories = ["command-line-interface"]
description = "A simple proc macro free Command Line Argument Parser"
keywords = ["args", "arguments", "cli", "parser", "parse"]
authors = [ "Michael Baykov <manpacket@gmail.com>" ]
readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/pacak/bpaf"

[dependencies]
bpaf_derive = { path = "./bpaf_derive", version = "0.1", optional = true }

[dev-dependencies]
strum = { version = "0.24", features = ["derive"] }
bpaf = { path = ".", version = "0.3", features = ["derive"] }


[features]
derive = ["bpaf_derive"]

[workspace]
members = [".", "./bpaf_derive"]
